version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6-buster
      - test-3.7-buster
      - test-3.8-rc-buster
jobs:
  test-3.7-buster: &test-template
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get -y update
            sudo apt-get -y install \
              -o APT::Install-Suggests=false \
              -o APT::Install-Recommends=false \
              qemu qemu-system-arm qemu-system-x86 \
              libvirt-dev libvirt-daemon libvirt-daemon-system \
              libvirt-clients nmap
            virtualenv cowrie-env
            . cowrie-env/bin/activate
            pip install libvirt-python==5.5.0
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run:
          command: |
            . cowrie-env/bin/activate
            flake8 --count --application-import-names cowrie --max-line-length=120 --statistics src
            python setup.py build sdist bdist
            make -C docs html
      - run:
          command: |
            . cowrie-env/bin/activate
            PYTHONPATH=`pwd`/src trial cowrie
  test-3.6-buster:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-buster
  test-3.8-rc-buster:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-rc-buster
