version: 2
jobs:
  build:  # required for runs that don't use workflows
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: |
            virtualenv ../cowrie-env
            ../cowrie-env/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run:
          command: |
            flake8 --count --application-import-names cowrie --max-line-length=120 --statistics .
            python setup.py build sdist bdist
            make -C docs html
      - run:
          command: |
            PYTHONPATH=`pwd`/src trial cowrie
