---
name: pypi-publish

on:  # yamllint disable-line rule:truthy
  push:
    # Publish only `tags` to pypi.org
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'pypi upload'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cowrie
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: "3.13"
          cache: pip

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools setuptools-scm twine wheel

      - name: Build and check
        run: |
          SETUPTOOLS_SCM_OVERRIDES_FOR_COWRIE='{local_scheme="no-local-version"}' python -m build
          twine check --strict dist/*

      - name: Publish package distributions to PyPI
        if: ${{ github.repository == 'cowrie/cowrie' }}
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          verbose: true
          print-hash: true
          verify-metadata: false

      - name: Sleep for publishing
        run: sleep 60s
        shell: bash

      - name: Download and test package
        if: ${{ github.repository == 'cowrie/cowrie' }}
        run: |
          python -m pip install cowrie
          twistd cowrie
