---
name: test-pypi

on:  # yamllint disable-line rule:truthy
  push:
    # Publish `main` as to test.pypi.org
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'test-pypi upload'

jobs:
  test-pypi-publish:
    name: Upload commit to PyPI
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/cowrie
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here, need fetch-depth to get metadata for version
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools twine wheel

      - name: Build and check
        run: |
          SETUPTOOLS_SCM_OVERRIDES_FOR_COWRIE='{local_scheme="no-local-version"}' python -m build
          twine check --strict dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Download and test package
        run: |
           python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ cowrie
           twistd cowrie
